### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by teutoburg**
## Correct loggers

Until now, our logging here used the _root logger_, which is the result of simply running `logging.warning()/error()/etc` without any other configuration. This is not ideal for a number of reasons and also "strongly advised" against in [the docs](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library). There are now three separate [`Loggers`](https://docs.python.org/3/howto/logging.html#loggers), one for each module (`core` and `ui`) and one top level logger for the package. As per the same paragraph in said docs, I included a [`NullHandler`](https://docs.python.org/3/library/logging.handlers.html#logging.NullHandler) to the top logger.

## Interoperability

In line with the planned changes in our other packages, all logger names start with `"astar."`, so it will be easy to collect all logging from all our packages if used together in the future.

### CODE REVIEW

**Comment by teutoburg** [comment]
Codecov diff hit fails because many of the logging calls here are triggered by conditions which are not tested 🙄

**Comment by teutoburg** [comment]
## Still TODO

As the name suggests, `skycalc_ipy` is intended to (also) be used from interactive IPython sessions. In this use case, it is unlikely that logging will be configured externally, but we might still want to give the user an easy option to receive logging messages. For the future, I thus propose to:

- [ ] Add a "verbose" option to `SkyCalc`
This would internally configure a console handler for our loggers. We might want to set this to `True` by default.
- [ ] Allow different levels of verbosity
- [ ] Add more (info, debug) logging for normal operation

And eventually maybe
- [ ] Split the interface for interactive use and internal use
Maybe this is already done with `ui.get_almanac_data()` in some places? Anyway, if the function/class used when `skycalc_ipy` is imported as a library in the background (e.g. in ScopeSim) is different from the one used interactively, the verbosity options discussed above might be easier to configure.

**Review by hugobuddel — COMMENTED** [review]
Good!

I don't think we have to spend much effort into improving the logging of skycalc_ipy per se. However, I think your goal is to improve logging in all our projects, and from that perspective it is good to experiment here first.

**Review by hugobuddel — APPROVED** [review]

**Comment by teutoburg** [comment]
> However, I think your goal is to improve logging in all our projects, and from that perspective it is good to experiment here first.

Indeed that was the idea 🙂

**Comment by teutoburg** [comment]
Urgh, now this has conflicts because I merged #43 first

**Comment by hugobuddel** [comment]
> Urgh, now this has conflicts because I merged #43 first

Sounds like you were fhlogging yourself!

Nooooo... I'll let myself out. It's Monday..

**Pull request merged**
