### PR TITLE
Prepare for v0.3.0

### PR DESCRIPTION
**Pull request by teutoburg**
Hopefully the last time we do this manually...

### CODE REVIEW

**Comment by hugobuddel** [comment]
> Hopefully the last time we do this manually...

Certainly. Apparently I forgot to actually make a 0.2.0 release on github... I'll still do that if I can find the correct commit

**Comment by hugobuddel** [comment]
v0.2.0 tag and release created. This should help with the automatic release notes as well

**Comment by teutoburg** [comment]
Aaargh, I messed up the new publish workflow 😞

**Comment by teutoburg** [comment]
I'll fix it and publish the new release later today...

**Comment by hugobuddel** [comment]
OK; if you wish I can also make a manual release

**Comment by teutoburg** [comment]
I could do that as well. But the automated version should be an easy fix.

**Pull request merged**
